export const items = [
  {
    id: "recipe-app",
    bannerImg: require("../../images/code/recipe.png"),
    title: "Recipe App",
    to: "/code/recipe-app",
    tagline: "My Recipe App",
    short: "Personal recipe app.",
    date: "may - june 2024",
    role: "designer, programmer",
    stack: "Next.js, Prisma, PostgreSQL",
    purpose: "personal",
    description:
      'I created my own personal recipe app because I couldn\'t find any existing ones that were free and had all the functionality I needed. <br><br>Features include creating and editing your own recipes, making comments on other recipes, and searching/filtering for your next meal. <br><br>View the project <a href="https://recipe-app-tau-ruddy.vercel.app/" target="_blank" rel="noopener noreferrer">here.</a>',
    images: [
      require("../../images/code/recipe1.png"),
      require("../../images/code/recipe2.png"),
      require("../../images/code/recipe4.png"),
      require("../../images/code/recipe3.png"),
    ],
  },
  {
    id: "fe-viz",
    bannerImg: require("../../images/code/feviz.png"),
    title: "Fire Emblem Visualizations",
    to: "/code/fe-viz",
    tagline: "Fire Emblem Visualizations",
    short:
      "Senior Thesis Independent Project for Spring 2024, in fulfillment of Princeton University's Bachelor of Arts in Computer Science.",
    date: "september 2023 - april 2024",
    role: "researcher, designer, programmer",
    stack: "React.js, D3.js, Flask, Python, ktrain",
    purpose: "school project",
    description:
      'Senior Thesis Independent Project for Spring 2024, in fulfillment of Princeton University\'s Bachelor of Arts in Computer Science.<br><br>A collection of visual essays and interactive data visualizations examining the intersection between technology, culture, storytelling, and video games through the lens of the Fire Emblem series.<br><br>View the project <a href="https://fireemblemviz.onrender.com/" target="_blank" rel="noopener noreferrer">here.</a><br>Read the written report <a href="https://drive.google.com/file/d/1rrZtRCRVQZJ9grFDnioefNDvUXXhA1Ay/view" target="_blank" rel="noopener noreferrer">here.</a>',
    images: [
      require("../../images/code/feviz1.png"),
      require("../../images/code/feviz2.png"),
      require("../../images/code/feviz3.png"),
      require("../../images/code/feviz4.png"),
      require("../../images/code/feviz5.png"),
      require("../../images/code/feviz6.png"),
    ],
  },
  {
    id: "iw-spring-2023",
    bannerImg: require("../../images/code/iw-banner.png"),
    title: "Music Generation Based on Self-Organization and Emergent Patterns",
    to: "/code/iw-spring-2023",
    tagline:
      "Music Generation Based on Self-Organization and Emergent Patterns",
    short:
      "Junior Independent Work Project for Spring 2023, in fulfillment of Princeton University's Bachelor of Arts in Computer Science.",
    date: "february - may 2023",
    role: "researcher, designer, programmer",
    stack: "React.js, Max/MSP",
    purpose: "school project",
    description:
      'Junior Independent Work Project for Spring 2023, in fulfillment of Princeton University\'s Bachelor of Arts in Computer Science.<br><br>An investigation of the underlying mechanisms of improvisation and musical emergence through the lens of self-organization. Provides a synthesis of previous research, proposes an algorithm for music generation using emergent patterns, and evaluates key pieces to analyze how a larger-scale program would function.  <br><br>View the project <a href="https://tvu20.github.io/iw-spring-2023/" target="_blank" rel="noopener noreferrer">here.</a><br>Read the written report <a href="https://drive.google.com/file/d/1TuHJZaiXfkjzxMti0a2fzbsssisLfaee/view?usp=sharing" target="_blank" rel="noopener noreferrer">here.</a>',
    images: [
      require("../../images/code/iw-1.png"),
      require("../../images/code/iw-2.png"),
      require("../../images/code/iw-3.png"),
      require("../../images/code/iw-4.png"),
      require("../../images/code/iw-5.png"),
    ],
  },
  {
    id: "spacetiger",
    bannerImg: require("../../images/code/spacetiger-banner.png"),
    title: "SpaceTiger",
    to: "/code/spacetiger",
    date: "august - december 2022",
    role: "creator, designer, front-end developer",
    stack: "Flask, SQLAlchemy, React.js, MaterialUI",
    purpose: "school project",
    tagline: "SpaceTiger",
    short:
      "A website for searching and reviewing spots on campus, whether it be for studying, partying, rehearsing, or just hanging out. ",
    description:
      'Final project for COS 333: Advanced Programing Techniques.<br><br>Part of <a href="https://tigerapps.org/" target="_blank" rel="noopener noreferrer">TigerApps</a>, a collection of student-developed apps designed to improve the academic and campus experience for Princeton students.  <br><br>A website for searching and reviewing spots on campus, whether it be for studying, partying, rehearsing, or just hanging out. <br><br>View the project <a href="https://spacetiger.tigerapps.org/" target="_blank" rel="noopener noreferrer">here.</a>',
    images: [
      require("../../images/code/spacetiger-1.png"),
      require("../../images/code/spacetiger-2.png"),
      require("../../images/code/spacetiger-4.png"),
      require("../../images/code/spacetiger-5.png"),
      require("../../images/code/spacetiger-6.png"),
    ],
  },
  {
    id: "war-and-peace",
    bannerImg: require("../../images/code/tolstoy-banner.png"),
    title: "War and Peace",
    to: "/code/war-and-peace",
    tagline: "War and Peace",
    short:
      "An interactive data visualization project inspired by the novel <i>War and Peace.</i>",
    date: "july 2022",
    role: "designer, programmer",
    stack: "React.js, d3, Python",
    purpose: "internship",
    description:
      'Created as an independent project for Red Hat HACk Week 2022. <br><br>An interactive data visualization project inspired by the novel <i>War and Peace.</i><br><br>View the project <a href="https://tvu20.github.io/war-and-peace/" target="_blank" rel="noopener noreferrer">here.</a>',
    images: [
      require("../../images/code/tolstoy-1.png"),
      require("../../images/code/tolstoy-2.png"),
      require("../../images/code/tolstoy-3.png"),
      require("../../images/code/tolstoy-4.png"),
    ],
  },
  {
    id: "campus",
    bannerImg: require("../../images/code/campus-banner.png"),
    title: "campus",
    to: "/code/campus",
    tagline: "campus",
    short:
      "Essential information for Princeton students, including dining hall menus, deals on the street, sports games coming up, and more.",
    date: "july - august 2021",
    role: "front-end developer",
    stack: "Flask, Firebase, React.js",
    purpose: "client work",
    description:
      'Developed with The Daily Princetonian Tech Team. <br><br>A progressive web app providing essential information for Princeton students, including dining hall menus, deals on the street, sports games coming up, and more.<br><br>View the project <a href="https://campus.dailyprincetonian.com/" target="_blank" rel="noopener noreferrer">here.</a>',
    images: [
      require("../../images/code/campus-1.png"),
      require("../../images/code/campus-2.png"),
      require("../../images/code/campus-3.png"),
      require("../../images/code/campus-4.png"),
      require("../../images/code/campus-5.png"),
      require("../../images/code/campus-6.png"),
    ],
  },
  {
    id: "sponsored",
    bannerImg: require("../../images/code/sponsored-banner.png"),
    title: "sponsored",
    to: "/code/sponsored",
    tagline: "sponsored",
    short:
      "A platform where students can learn about new opportunities and create meaningful connections with recruiters.",
    date: "july 2021",
    role: "team lead, full-stack developer",
    stack: "Flask, Firebase, React.js",
    purpose: "client work",
    description:
      'Developed with The Daily Princetonian Tech Team. <br><br>A platform where students can learn about new opportunities and create meaningful connections with recruiters.<br><br>View the project <a href="https://sponsored.dailyprincetonian.com/" target="_blank" rel="noopener noreferrer">here.</a>',
    images: [
      require("../../images/code/sponsored-1.png"),
      require("../../images/code/sponsored-2.png"),
      require("../../images/code/sponsored-3.png"),
      require("../../images/code/sponsored-4.png"),
    ],
  },
];
