export const items = [
  {
    id: "moon-festival",
    bannerImg: require("../../images/art/moon-banner.jpg"),
    title: "moon festival",
    to: "/art/moon-festival",
    date: "august 2023",
    type: "digital illustration",
    software: "procreate",
    purpose: "personal",
    description: "Some scenes from the Autumn Moon Festival in Vietnam.",
    images: [require("../../images/art/moon-festival.jpg")],
  },
  {
    id: "autumn-rewind",
    bannerImg: require("../../images/art/autumn-banner.png"),
    title: "Autumn Rewind",
    to: "/art/autumn-rewind",
    date: "january 2023",
    type: "poster",
    software: "procreate, photoshop",
    purpose: "client work",
    description:
      "Poster design for \"Autumn Rewind\" by Le'Naya Wilkerson '25, produced by Theatre Intime.",
    images: [
      require("../../images/art/autumn-1.png"),
      require("../../images/art/autumn-2.png"),
      require("../../images/art/autumn-3.png"),
    ],
  },
  {
    id: "twelfth-night",
    bannerImg: require("../../images/art/twelfth-banner.png"),
    title: "Twelfth Night",
    to: "/art/twelfth-night",
    date: "november 2022",
    type: "poster",
    software: "procreate, photoshop",
    purpose: "client work",
    description:
      'Poster design for "Twelfth Night" by William Shakespeare, produced by Theatre Intime.',
    images: [require("../../images/art/twelfth-1.png")],
  },
  {
    id: "intro-to-ideation",
    bannerImg: require("../../images/art/ideation-banner.jpg"),
    title: "Intro to Ideation",
    to: "/art/intro-to-ideation",
    date: "july 2022",
    type: "book cover",
    software: "procreate, photoshop",
    purpose: "personal",
    description:
      'Book cover design for "Intro to Ideation: 70 Design Thinking Exercises" by Rohit Narayanan.',
    images: [require("../../images/art/ideation-banner.jpg")],
  },
  {
    id: "little-town",
    bannerImg: require("../../images/art/town-banner.png"),
    title: "Little Town",
    to: "/art/little-town",
    date: "may 2022",
    type: "animation",
    software: "procreate, adobe after effects",
    purpose: "school project",
    description:
      'Final project for VIS 220: Digital Animation.<br><br>A day in the life.<br><br>Watch the full animation <a href="https://vimeo.com/704788394" target="_blank" rel="noopener noreferrer">here.</a>',
    images: [require("../../images/art/town-banner.png")],
  },
  {
    id: "54-peoples",
    bannerImg: require("../../images/art/peoples-banner.png"),
    title: "54 Peoples",
    to: "/art/54-peoples",
    date: "may 2021",
    type: "illustration",
    software: "photoshop",
    purpose: "school project",
    description:
      "Final project for FRS 174: Drawing Data. <br><br>The 54 ethnic groups of Vietnam, drawn in traditional and modern clothing.",
    images: [
      require("../../images/art/peoples.png"),
      require("../../images/art/peoples-modern.png"),
    ],
  },
  {
    id: "unconference",
    bannerImg: require("../../images/art/unconference-banner.png"),
    title: "UnConference",
    to: "/art/unconference",
    date: "april 2021",
    type: "design",
    software: "adobe illustrator, adobe indesign",
    purpose: "client work",
    description:
      "Key visuals, posters, and handouts for UnConference 2021, hosted by IgniteSTEM Princeton.",
    images: [
      require("../../images/art/unconference-1.png"),
      require("../../images/art/unconference-2.png"),
      require("../../images/art/unconference-3.png"),
      require("../../images/art/unconference-4.png"),
    ],
  },
  {
    id: "atla-movement-studies",
    bannerImg: require("../../images/art/movement-banner.png"),
    title: "atla: movement studies",
    to: "/art/atla-movement-studies",
    date: "march 2021",
    type: "animation",
    software: "adobe photoshop",
    purpose: "school project",
    description:
      'Project for FRS 174: Drawing Data. <br><br> Movement studies, using benders from <i>Avatar: The Last Airbender</i> as reference.<br><br>Watch the animation <a href="https://drive.google.com/file/d/1gsykFDZHO3jTJOHY9z6zV3fJGm4B0mWW/view?usp=sharing" target="_blank" rel="noopener noreferrer">here.</a>',
    images: [require("../../images/art/movement-1.png")],
  },
  {
    id: "items-on-my-shelf",
    bannerImg: require("../../images/art/shelf-banner.jpg"),
    title: "items on my shelf",
    to: "/art/items-on-my-shelf",
    date: "february 2021",
    type: "illustration",
    software: "adobe photoshop",
    purpose: "school project",
    description:
      "Project for FRS 174: Drawing Data. <br><br> Some items on my shelf.",
    images: [require("../../images/art/documentarydrawing.jpg")],
  },
  {
    id: "kaboom",
    bannerImg: require("../../images/art/caelynn-banner.png"),
    title: "KABOOM!",
    to: "/art/kaboom",
    date: "may 2020",
    type: "illustration",
    software: "adobe photoshop",
    purpose: "personal",
    description:
      "Practice illustrating in the style of <i>Into the Spiderverse</i>.",
    images: [require("../../images/art/caelynn.png")],
  },
  {
    id: "rainbow-squid",
    bannerImg: require("../../images/art/squid-banner.png"),
    title: "rainbow squid",
    to: "/art/rainbow-squid",
    date: "december 2019",
    type: "illustration",
    software: "adobe illustrator",
    purpose: "personal",
    description: "A redraw of a previous illustration from high school.",
    images: [
      require("../../images/art/squid-1.PNG"),
      require("../../images/art/squid-2.PNG"),
    ],
  },
  {
    id: "sweeney-todd",
    bannerImg: require("../../images/art/sweeney-banner.png"),
    title: "Sweeney Todd",
    to: "/art/sweeney-todd",
    date: "october 2019",
    type: "poster",
    software: "firealpaca, adobe photoshop",
    purpose: "client work",
    description:
      'Poster design for "Sweeney Todd: The Demon Barber of Fleet Street" by Stephen Sondheim, produced by The Lawrenceville School.',
    images: [require("../../images/art/sweeney-1.png")],
  },
  {
    id: "wither",
    bannerImg: require("../../images/art/wither-banner.png"),
    title: "Wither",
    to: "/art/wither",
    date: "june 2019",
    type: "illustration",
    software: "firealpaca",
    purpose: "client work",
    description: "Illustrations for a poetry collection.",
    images: [
      require("../../images/art/wither-1.png"),
      require("../../images/art/wither-2.png"),
      require("../../images/art/wither-3.png"),
      require("../../images/art/wither-4.png"),
      require("../../images/art/wither-5.png"),
      require("../../images/art/wither-6.png"),
    ],
  },

  {
    id: "winterfest",
    bannerImg: require("../../images/art/winterfest-banner.png"),
    title: "Winterfest",
    to: "/art/winterfest",
    date: "january 2019",
    type: "poster",
    software: "firealpaca",
    purpose: "client work",
    description:
      'Poster design for "Winterfest", an annual festival of one-act plays produced by The Lawrenceville School.',
    images: [require("../../images/art/winterfest-1.png")],
  },
  {
    id: "moana",
    bannerImg: require("../../images/art/moana-banner.png"),
    title: "moana",
    to: "/art/moana",
    date: "january 2017",
    type: "illustration",
    software: "firealpaca",
    purpose: "personal",
    description: "Disney princess drawing practice.",
    images: [require("../../images/art/moana-1.png")],
  },
];
